name: robowski
channels:
  - viscid-hub
  - conda-forge
  - https://conda.anaconda.org/openeye
  - defaults
dependencies:
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - blas=1.0
  - ca-certificates
  - colorama=0.4.6
  - cycler=0.11.0
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - freetype=2.10.1
  - icu=58.2
  - importlib_metadata=1.5.0
  - iniconfig=2.0.0
  - ipykernel=5.5.5
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - joblib=1.3.2
  - jpeg=9c
  - jupyter_client=7.1.2
  - kiwisolver=1.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - matplotlib=3.1.0
  - matplotlib-base=2.2.4
  - matplotlib-inline=0.1.7
  - mkl=2020.4
  - mkl-service=2.0.2
  - nest-asyncio=1.6.0
  - openssl=1.1.1f
  - pandas=0.25.3
  - parso=0.8.4
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pip=24.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.48
  - pygments=2.17.2
  - pyparsing=3.1.4
  - pyqt=5.9.2
  - pytest=7.4.4
  - python=3.7.3
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pytz=2024.2
  - qt=5.9.7
  - qtconsole=4.5.1
  - qtpy=1.8.0
  - scikit-learn=0.21.2
  - scipy=1.5.2
  - seaborn=0.10.1
  - setuptools=59.8.0
  - shortuuid=1.0.13
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.30.1
  - statsmodels=0.10.0
  - tomli=2.0.2
  - traitlets=5.9.0
  - uncertainties=3.1.2
  - vtk=8.1.2
  - wcwidth=0.2.10
  - wheel=0.42.0
  - xlrd=1.2.0
  - zeromq=4.3.2
  - zipp=3.7.0
  - zlib=1.2.11
  - pip:
    - aiofiles==22.1.0
    - aiosqlite==0.19.0
    - anyio==3.7.1
    - apptools==4.5.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - attrs==24.2.0
    - babel==2.14.0
    - beautifulsoup4==4.13.4
    - bleach==6.0.0
    - cached-property==1.5.2
    - certifi==2025.4.26
    - cffi==1.15.1
    - charset-normalizer==3.4.2
    - configobj==5.0.9
    - corner==2.2.1
    - defusedxml==0.7.1
    - emcee==3.1.6
    - envisage==4.9.2
    - et-xmlfile==1.1.0
    - fastjsonschema==2.21.1
    - fqdn==1.5.1
    - idna==3.10
    - importlib-resources==5.12.0
    - isoduration==20.11.0
    - jinja2==3.1.6
    - json5==0.9.16
    - jsonpointer==3.0.0
    - jsonschema==4.17.3
    - jupyter-core==4.12.0
    - jupyter-events==0.6.3
    - jupyter-server==1.24.0
    - jupyter-server-fileid==0.9.3
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.5
    - jupyterlab==3.6.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - markupsafe==2.1.5
    - mayavi==4.7.2
    - mistune==3.0.2
    - mouseinfo==0.1.3
    - nbclassic==1.2.0
    - nbclient==0.7.4
    - nbconvert==7.6.0
    - nbformat==5.8.0
    - networkx==2.6.2
    - notebook==6.5.7
    - notebook-shim==0.2.4
    - numpy==1.19.5
    - packaging==24.0
    - pandocfilters==1.5.1
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.17.1
    - pyautogui==0.9.47
    - pycparser==2.21
    - pyface==7.1.0
    - pygetwindow==0.0.9
    - pymsgbox==1.0.9
    - pyperclip==1.9.0
    - pyqt5==5.15.0
    - pyqt5-sip==12.8.0
    - pyrect==0.2.0
    - pyrsistent==0.19.3
    - pyscreeze==1.0.1
    - python-json-logger==3.0.1
    - pytweening==1.2.0
    - pyyaml==6.0.1
    - pyzmq==26.2.1
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - send2trash==1.8.3
    - sniffio==1.3.1
    - soupsieve==2.4.1
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.64.1
    - traits==6.1.1
    - traitsui==7.1.0
    - uri-template==1.3.0
    - urllib3==2.0.7
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - y-py==0.6.2
    - ypy-websocket==0.8.4
